# configuration for https://github.com/EmbarkStudios/cargo-deny

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
    "Unlicense",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "Unicode-DFS-2016",
    "MPL-2.0",
    "ISC",
    "CC0-1.0",
    "BUSL-1.1",
    "GPL-2.0",
    "OpenSSL",
]

[advisories]
version = 2

[bans]
multiple-versions = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]